import type { PageId } from '../../shared/types'

export const pageTitles: Record<PageId, string> = {
  dashboard: 'Dashboard',
  stacks: 'Stack Manager',
  containers: 'Containers',
  images: 'Images',
  health: 'Health Monitor',
  uptime: 'Uptime Monitor',
  networks: 'Networks',
  volumes: 'Volumes',
  bookmarks: 'Bookmarks',
  activity: 'Activity',
  maintenance: 'Maintenance',
  environment: 'Environment',
  backup: 'Backup & Restore',
  logs: 'Logs',
  system: 'System Info',
  diagnostics: 'Diagnostics',
  users: 'User Management',
  config: 'Server Config',
  settings: 'Settings',
  terminal: 'Terminal',
  cronjobs: 'Cron Jobs',
  trends: 'Resource Trends',
  updates: 'Image Updates',
  notifications: 'Notifications',
  snapshots: 'Snapshots',
  templates: 'Templates',
  automations: 'Automations',
  topology: 'Network Topology',
  'file-browser': 'File Browser',
  'disk-analysis': 'Disk Analysis',
  secrets: 'Secrets Manager',
  schedules: 'Scheduled Tasks',
  plugins: 'Plugins',
  'event-feed': 'Live Events',
  export: 'Export Center',
  setup: 'Setup Wizard',
}
