#!/usr/bin/env node
// =============================================================================
// theme-classes — the inventory of Tailwind colour classes the dashboard uses
// (status hues, slate, white, black), written to src/renderer/lib/themeClasses.ts.
// The theme engine restyles exactly these for every look, so a class a page
// starts using is themed as soon as the inventory knows it.
//   node scripts/theme-classes.mjs          rewrite the inventory
//   node scripts/theme-classes.mjs --check  exit 1 when it is out of date (CI)
// =============================================================================

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
export const INVENTORY = path.join(root, 'src/renderer/lib/themeClasses.ts')
/** files that list classes for the engine's own use and must not count as usage */
const SKIP = new Set([INVENTORY, path.join(root, 'src/renderer/lib/themeEngine.ts')])

export const HUES = ['emerald', 'teal', 'lime', 'green', 'amber', 'orange', 'yellow', 'rose', 'red', 'cyan', 'sky', 'blue', 'slate', 'white', 'black',
  // decorative hues (no palette role): their pale text steps are darkened in a light look so they stay readable
  'violet', 'purple', 'fuchsia', 'pink', 'indigo']
/** the state variants the engine can restyle (responsive ones like sm: would need their media query) */
const VARIANT = '(?:hover:|focus:|focus-visible:|focus-within:|active:|group-hover:|placeholder:|file:)?'
const PROP = '(?:bg|text|border(?:-[tblrxy])?|ring-offset|ring|from|to|via|fill|stroke|shadow|divide|accent|placeholder)'
const CLASS_RE = new RegExp(`(?<![\\w:-])(${VARIANT}${PROP}-(?:${HUES.join('|')})(?:-\\d{2,3})?(?:\\/(?:\\d{1,3}|\\[[\\d.]+\\]))?)(?![\\w\\-/\\[.])`, 'g')

function walk(dir, acc = []) {
  for (const name of fs.readdirSync(dir)) {
    const p = path.join(dir, name)
    if (fs.statSync(p).isDirectory()) walk(p, acc)
    else if (/\.(tsx|ts)$/.test(name) && !SKIP.has(p)) acc.push(p)
  }
  return acc
}

export function scanClasses() {
  const found = new Set()
  for (const file of [path.join(root, 'index.html'), ...walk(path.join(root, 'src/renderer'))]) {
    for (const m of fs.readFileSync(file, 'utf8').matchAll(CLASS_RE)) found.add(m[1])
  }
  return [...found].sort()
}

export function renderInventory(classes) {
  const lines = []
  let line = ' '
  for (const c of classes) {
    const item = ` '${c}',`
    if (line.length + item.length > 118) { lines.push(line); line = ' ' }
    line += item
  }
  if (line.trim()) lines.push(line)
  return [
    '// =============================================================================',
    '// The Tailwind colour classes the dashboard uses (status hues, slate, white and',
    '// black) — the theme engine restyles exactly these for every look.',
    '// Generated by scripts/theme-classes.mjs; CI fails when it is out of date.',
    '// =============================================================================',
    '',
    'export const THEME_CLASSES: readonly string[] = [',
    ...lines,
    ']',
    '',
  ].join('\n')
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const text = renderInventory(scanClasses())
  const current = fs.existsSync(INVENTORY) ? fs.readFileSync(INVENTORY, 'utf8') : ''
  if (process.argv.includes('--check')) {
    if (current !== text) {
      console.error('src/renderer/lib/themeClasses.ts is out of date: run node scripts/theme-classes.mjs')
      process.exit(1)
    }
    console.log('theme class inventory is up to date')
  } else if (current !== text) {
    fs.writeFileSync(INVENTORY, text)
    console.log(`wrote ${path.relative(root, INVENTORY)}`)
  } else {
    console.log('theme class inventory unchanged')
  }
}
